### ISSUE TITLE
Plan of code release? And the paper link?

### ISSUE THREAD

**Issue by mailnhonig** [hzhao1997/HF-Avatar#1]
Hi! I'm looking forword to learn your remarkable work, and seems like you forget this repo. Could you offer me the paper link? The results shown in the project page is amazing!
Besides, what is your plan to release the code?

**Comment by hzhao1997** [comment]
> 

Sorry for the late reply and thanks for your attention. Now the paper is available and we are cleaning the code now.

**Comment by hzhao1997** [comment]
The code is available now.
