### ISSUE TITLE
跑其它输入的视频数据 ，效果没有那么好

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#13]
![image](https://user-images.githubusercontent.com/94040073/206717997-2ef0701a-ee6f-4c22-be35-3d8ad45fd533.png)

你好，我有一个问题想请教你，麻烦你能解答一下，我用别的视频跑出来的结果有以下问题 
1、是鼻子那里多生成了一块
2、是手的位置是黑的
是否对视频数据有什么要求呢？我没有改动任何位置的代码

**Comment by wusidong** [comment]
![image](https://user-images.githubusercontent.com/94040073/206719780-11f7ff93-1420-4e84-9a52-93f18dd1fd32.png)
体型也变小了

**Comment by hzhao1997** [comment]
之前的一版代码姿态初始化有一些问题，目前我更新了代码，可以再尝试一下。

**Comment by hzhao1997** [comment]
另外手部黑的问题，我的方法暂时无法避免。

**Comment by wusidong** [comment]
非常感谢你的答复，我会重新尝试跑新的代码，还有一个疑问是头发是否能生成呢，如果输入的视频中目标人物是有很多头发的，生成的三维模型有头发吗？

**Comment by hzhao1997** [comment]
我的方法不支持头发生成
