### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by Yuanhong200727** [hzhao1997/HF-Avatar#15]
当我用项目给的data_dir（sample_data）运行dynamic_offsets_runner.py时出现了报错：
![错误](https://user-images.githubusercontent.com/117512740/209962998-0134e2cb-bc47-4b9c-a6ab-190d339b7cea.jpg)
请问这是什么原因呢？

**Comment by hzhao1997** [comment]
我采用的pytroch3d版本为0.4.0， 其他版本如0.7.1不能保证正常运行
