### ISSUE TITLE
smpl_sampling.pkl

### ISSUE THREAD

**Issue by Yuanhong-Zheng** [hzhao1997/HF-Avatar#16]
Hi，我遇到了一个问题。
当我运行
python _infer_single.py --root_dir $data_dir --name $subject_name
时报错：
`IOError: [Errno 2] No such file or directory: '/home/zhengyuanhong/Downloads/HF-Avatar/thirdparty/octopus/model/../assets/smpl_sampling.pkl'`
请问这是什么文件呢？

**Comment by hzhao1997** [comment]
https://github.com/thmoa/octopus/tree/master/assets 需要下载这个文件下的文件
