### ISSUE TITLE
octopus环境配置

### ISSUE THREAD

**Issue by JunfengLiu1** [hzhao1997/HF-Avatar#20]
请问octopus有没有python3版本的代码呢，RTX30系显卡要安装tensorflow1只能用python3，或者怎样在tf2上运行octopus呢，感谢！

**Comment by MilesTheProwler** [comment]
Hi, did you run sucessfully ?

**Comment by JunfengLiu1** [comment]
> Hi, did you run sucessfully ?

Yeah，I run successfully.NVIDIA provide a way to use tf1 in RTX30 series card or higher.

**Comment by MilesTheProwler** [comment]
I can sucessfully run on GTX 1080 ti but I cannot run on my RTX 3060 . I got many errors like Dirt, neural renderer etc.. Could you please help me from wechat ? 

Thanks.

**Comment by JunfengLiu1** [comment]
> I can sucessfully run on GTX 1080 ti but I cannot run on my RTX 3060 . I got many errors like Dirt, neural renderer etc.. Could you please help me from wechat ?
> 
> Thanks.

I run the octopus successfully even in my RTX4080 a few months a ago,but now I can't remember all the details.What's the exactly problem have you met?For me,is the difficulty to use tf1 in RTX30 or 40 series.After solving this,everything is ok.And about Dirt,I think the main problem is the TF,that was what I met before.

**Comment by MilesTheProwler** [comment]
Thank you for your reply. Yes, I have the problem with TF version on my RTX card . I cannot used TF version1.x on my RTX 3060 card. In addition, I also encountered cuda version 11 problem when I install Dirt. Could you share your environment with me and can I get your email or WeChat?

**Sample Errors :** 
```
Processing sample...
> Optimizing for pose...
  0%|                                                                                                                                                                                                                 | 0/10 [00:00<?, ?it/s]2023-08-22 16:24:18.296359: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2023-08-22 16:25:50.156420: I tensorflow/core/kernels/cuda_solvers.cc:159] Creating CudaSolver handles for stream 0x55fa094fdcf0
2023-08-22 16:26:08.284736: E tensorflow/stream_executor/cuda/cuda_blas.cc:698] failed to run cuBLAS routine cublasGemmBatchedEx: CUBLAS_STATUS_EXECUTION_FAILED
2023-08-22 16:26:08.284773: E tensorflow/stream_executor/cuda/cuda_blas.cc:2620] Internal: failed BLAS call, see log for details
2023-08-22 16:26:08.326578: I tensorflow/stream_executor/stream.cc:5014] [stream=0x55fa0950bb90,impl=0x55fa093dbf20] did not memcpy device-to-host; source: 0x813bc6700
2023-08-22 16:26:08.326623: F tensorflow/core/framework/op_kernel.cc:1408] Check failed: nullptr == ctx->op_kernel().AsAsync() (nullptr vs. 0x55fa38108400)Use OP_REQUIRES_ASYNC in AsyncOpKernel implementations.
Aborted
```


Thanks.

**Comment by JunfengLiu1** [comment]
zyh2022200727@163.com,my email.Or you can send your WeChat using this，I think

**Comment by MilesTheProwler** [comment]
@JunfengLiu1 I already send email to you, please check it.

**Comment by muximuxi** [comment]
Can you share how to make dirt successfully on  3060 or 4090?  I failed make dirt with tf2.4.1 or tf2.11.1 on 4090, could you tell me how to solve it please?

**Comment by MilesTheProwler** [comment]
I think the problem can be solved with nvidia tensorflow version. I didn't test it yet.

**Comment by JunfengLiu1** [comment]
> Can you share how to make dirt successfully on 3060 or 4090? I failed make dirt with tf2.4.1 or tf2.11.1 on 4090, could you tell me how to solve it please?

I install tf1 with cuda11 successfully according to this website: http://t.csdn.cn/KOKjQ

**Comment by muximuxi** [comment]
> > Can you share how to make dirt successfully on 3060 or 4090? I failed make dirt with tf2.4.1 or tf2.11.1 on 4090, could you tell me how to solve it please?
> 
> I install tf1 with cuda11 successfully according to this website: http://t.csdn.cn/KOKjQ

请问你使用python版本是3.8吗？我用这个网址里面安装nvidia tensorflow 之后，去编译dirt , 执行到pip install -e . 这一步时，会自动去下载TensorFlow2.12版本的，然后提示python版本高于3.7了，就跳出安装了

**Comment by MilesTheProwler** [comment]
you can try to install with pip install -e . --no-deps 

Do you have wechat ? I have some questions to ask you, please share your wechat account with me

**Comment by muximuxi** [comment]
请问用nvidia tensorflow编译dirt 成功后，执行第一步，有遇到这种错误吗？ 请问怎么解决？
ValueError: Layer #5 (named "conv2d_1"), weight &lt;tf.Variable 'conv2d_1/kernel:0' shape=(3, 3, 8, 16) dtype=float32&gt; has shape (3, 3, 8, 16), but the saved weight has shape (8, 3, 3, 3).
