### ISSUE TITLE
脸的效果不自然，是否需要修改某个参数呢

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#21]
![238a93904c75bb6ec3008d6139a1e97](https://user-images.githubusercontent.com/94040073/225605286-386339d6-3140-48e9-a0b7-9cf4dbe11a1b.jpg)
![8f2bd979d9f8bc0b533849754abb669](https://user-images.githubusercontent.com/94040073/225605328-3df38ced-e1bd-4637-9354-dcb6654dd917.jpg)

**Comment by wusidong** [comment]
跑大部分的视频输入都有这个问题，生成的脸部不自然的问题怎么解决呢

**Comment by hzhao1997** [comment]
似乎几何重建有问题，麻烦把中间结果发我一下

**Comment by hzhao1997** [comment]
你是采用octopus作为姿态初始化吗？

**Comment by JunfengLiu1** [comment]
我也有同样的问题，请问如果想要得到高质量的模型（比如视频中的效果），需要注意哪些细节呢？

**Comment by wusidong** [comment]
> 你是采用octopus作为姿态初始化吗？

是的，没有改动任何代码

**Comment by wusidong** [comment]
> 似乎几何重建有问题，麻烦把中间结果发我一下

非常感谢！我整理一下发给你

**Comment by wusidong** [comment]
> > 似乎几何重建有问题，麻烦把中间结果发我一下
> 
> 非常感谢！我整理一下发给你


你好，抱歉我没有找到你的邮箱，你可以发一下你的邮箱给我，我给你发过去，或者你也可以选择访问我的云端的链接：
https://drive.google.com/drive/folders/13ZqPKeONgqJrnMj3Y8jovgvUFjs6KkQ6

**Comment by JunfengLiu1** [comment]
> 你是采用octopus作为姿态初始化吗？

@hzhao1997 请问只支持A-pose吗，我的视频人物是T-pose,用octopus进行初始化，最终重建的结果是否是一个合理的T-pose人物呢？

**Comment by wusidong** [comment]
![image](https://user-images.githubusercontent.com/94040073/230312246-47022196-ba63-44ae-a835-b7fb5ab9d485.png)
生成的几何形状有问题，脸部生成效果不太好

**Comment by hzhao1997** [comment]
> > 你是采用octopus作为姿态初始化吗？
> 
> @hzhao1997 请问只支持A-pose吗，我的视频人物是T-pose,用octopus进行初始化，最终重建的结果是否是一个合理的T-pose人物呢？

目前只能支持a-pose
