### ISSUE TITLE
几何重建出现问题

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#22]
![image](https://user-images.githubusercontent.com/94040073/230377121-d79704e5-93ab-4c43-aee0-56f1598988a7.png)
请问作者，在测试某些数据的时候，重建几何形状会出现问题，主要在于脸部几何形状，应该怎么解决这个问题呢

**Comment by hzhao1997** [comment]
https://github.com/hzhao1997/HF-Avatar/blob/c8dea235ff6d71fbac30bfeb838fc1d82d1958be/geometry_model/loss.py#L69 可以把脸部的lap loss提大一点

**Comment by wusidong** [comment]
好的，感谢回复！

**Comment by wusidong** [comment]
![image](https://user-images.githubusercontent.com/94040073/230558062-e0b29db1-e92e-4936-aced-857a51d81e87.png)
请问您作者，当我把isupsample改为True的时候，就会报这样的错误
