### ISSUE TITLE
如何选择isupsample=True

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#23]
你好，作者，我想让生成的三维模型精度更高一些，所以想选择上采样，但是当我在代码中修改isupsample=True时，就会报错，该如何修改呢？
![image](https://user-images.githubusercontent.com/94040073/230585961-9f053546-8a11-4eb4-af7b-c2f02f74d805.png)

**Comment by hzhao1997** [comment]
这部分只是优化姿态，https://github.com/hzhao1997/HF-Avatar/blob/c8dea235ff6d71fbac30bfeb838fc1d82d1958be/dynamic_offsets_runner.py#L320 
而https://github.com/hzhao1997/HF-Avatar/blob/c8dea235ff6d71fbac30bfeb838fc1d82d1958be/dynamic_offsets_runner.py#L335 是重建几何，默认就是isupsample=True

**Comment by wusidong** [comment]
好的，感谢回答！
