### ISSUE TITLE
脸部几何重建的问题

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#24]
![image](https://user-images.githubusercontent.com/94040073/232010501-41478244-8bd6-43ad-9b3b-6b4b81fdd888.png)
作者，我按照你的方式改了一下，把脸部的lap loss提大到了3200，鼻子的lap loss 改到了10，结果好了一些，但是脸部几何形状还是有一点问题，该如何修改呢？

**Comment by hzhao1997** [comment]
如果脸部lap loss改为更大呢， 比如32000

**Comment by wusidong** [comment]
好的，作者，我尝试一下参数改的更大，感谢回复！

**Comment by wusidong** [comment]
![image](https://user-images.githubusercontent.com/94040073/232991829-038a4285-3ef0-47ef-b708-86899a5e3c7b.png)
按您的方法尝试了一下，有效果！
