### ISSUE TITLE
纹理生成

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#25]
![image](https://user-images.githubusercontent.com/94040073/232994439-73596f30-ab69-466a-91ea-5628d59ea073.png)
你好，作者，我这个数据运行过两次，第一个用octopus进行了姿态优化，第二个没有用ctopus进行姿态优化，第一个生成的纹理脸部有点模糊，第二个生成的脸部比较清晰，怎么样才能使生成的纹理中脸部更加清晰呢？需要将哪个参数调大呢？

**Comment by hzhao1997** [comment]
https://github.com/hzhao1997/HF-Avatar/blob/c8dea235ff6d71fbac30bfeb838fc1d82d1958be/texture_model/lib.py#L55 可以在增大amplitude，但注意增大可能会引入图像噪声。

**Comment by wusidong** [comment]
好的，我去试一下，感谢回复！
