### ISSUE TITLE
about PIFuHD generate  normal data

### ISSUE THREAD

**Issue by ghost** [hzhao1997/HF-Avatar#26]
其中的npy文件是怎么获取到的，没有在PIFuHD的代码中找到，其中的lib/evaluator虽然有npy输出但是需要其他的文件，但是也没有找到中间产出的对应需求文件，请问这个normal file是怎么获取的 @hzhao1997

**Comment by wusidong** [comment]
你可以看 How to generate normals? #8，作者已经解答过这个问题了

**Comment by ghost** [comment]
> 你可以看看如何生成法线？#8，作者已经回答过这个问题了
谢谢哈，才注意到
