### ISSUE TITLE
如何生成新的姿态

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#28]
你好，作者，我按照你的代码已经实现了三维人体的重建，下面是它的一个结果，结果非常棒！我看你的论文里面，该方法可以实现新姿态的合成，这个功能应该如何实现呢？
![image](https://user-images.githubusercontent.com/94040073/234749104-f706dfce-6a0f-4f13-98b1-10c4185ab8d7.png)

**Comment by x-ray990011** [comment]
> 你好，作者，我按照你的代码已经实现了三维人体的重建，下面是它的一个结果，结果非常棒！我看你的论文里面，该方法可以实现新姿态的合成，这个功能应该如何实现呢？ ![image](https://user-images.githubusercontent.com/94040073/234749104-f706dfce-6a0f-4f13-98b1-10c4185ab8d7.png)

您好，可以交流一下吗，我的邮箱：sxpypp@126.com，我有其他的方法做脸部重建

**Comment by hzhao1997** [comment]
可以调用该行， https://github.com/hzhao1997/HF-Avatar/blob/c8dea235ff6d71fbac30bfeb838fc1d82d1958be/utils/data_generation.py#LL317C27-L317C27
通过输入不同的姿态参数得到相应的几何

**Comment by wusidong** [comment]
好的，感谢回复！
