### ISSUE TITLE
关于demo数据集的问题

### ISSUE THREAD

**Issue by xiegongsheldon** [hzhao1997/HF-Avatar#4]
如何产生sample数据集 normal文件夹下的npz文件，PIFuHD运行是能产生obj文件，是提取哪些内容存取成npz文件的？

**Comment by hzhao1997** [comment]
pifuhd生成的normal被存成了npz文件
请查看此行https://github.com/facebookresearch/pifuhd/blob/ee51fc23629c4afc99dbfd235c5b8bbd77a86aa2/apps/recon.py#L43
net.netG.nmlF是估计的normal

**Comment by xiegongsheldon** [comment]
> pifuhd生成的normal被存成了npz文件 请查看此行https://github.com/facebookresearch/pifuhd/blob/ee51fc23629c4afc99dbfd235c5b8bbd77a86aa2/apps/recon.py#L43 net.netG.nmlF是估计的normal

谢谢 我尝试一下～
