### ISSUE TITLE
输出的图片有误

### ISSUE THREAD

**Issue by myccver** [hzhao1997/HF-Avatar#6]
您好，请问我在按照要求运行了dynamic offset代码后，所有输出的图片是黑色的，这可能是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/66241749/201275378-fea3c727-aad8-40cf-ad30-dac324141e10.png)
与pytorch3d的版本有关系吗？我的pytorch3d版本是0.7.1，cuda版本是11.1.在运行代码的时候没有报错。

**Comment by myccver** [comment]
当我卸载pytorch3d0.7.1更换成0.4.0后问题得到了解决

**Comment by xiegongsheldon** [comment]
你那边能得到有纹理的三维人体模型吗？

**Comment by myccver** [comment]
> 

不能，跑完程序后我使用open3d读取obj文件，显示：
![image](https://user-images.githubusercontent.com/66241749/201956698-f6ce28c5-be27-4229-97a6-abc04a604376.png)

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。
