### ISSUE TITLE
如何得到有纹理的三维模型

### ISSUE THREAD

**Issue by xiegongsheldon** [hzhao1997/HF-Avatar#7]
请问如何将生成的texture map 应用到生成的initial geometry中呢？

**Comment by hzhao1997** [comment]
可调用此行https://github.com/hzhao1997/HF-Avatar/blob/d656820ef1224132ab0b417eb74018be8c797e60/geometry_model/network.py#L537 保存为textured mesh，然后用meshlab查看

**Comment by xiegongsheldon** [comment]
> write_tpose_obj

能否详细解说一下在哪里调用这个函数能生成带衣服纹理的obj文件呢 谢谢了

**Comment by ZhangLei999** [comment]
同问

**Comment by hzhao1997** [comment]
最后把生成的texture.png放入相应的文件夹内

**Comment by xiegongsheldon** [comment]
> 最后把生成的texture.png放入相应的文件夹内
你在使用说明里先执行这个脚本
dynamic_offsets_runner.py 生成不带颜色的三维模型，然后接下来执行的另一个脚本生成texture.png，那咋么把这个png文件渲染在这个三维模型里头去生成obj文件呢？ 你说的是放在哪个文件夹里呢

**Comment by hzhao1997** [comment]
![M`Z1VHPN$A%VK HFI1OM`5P](https://user-images.githubusercontent.com/32841739/205050817-0ad62c43-a1b1-4616-91ba-cfdee5ac2101.png)
如图所示，将生成的数据文件放入一个文件夹内即可用meshlab打开

**Comment by ZhangLei999** [comment]
试过，可行，非常感谢

**Comment by ZhangLei999** [comment]
顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准

**Comment by weiforce** [comment]
> 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准

https://github.com/NVlabs/instant-ngp
参考这个

**Comment by wusidong** [comment]
你好，请问你生成三维模型的效果是什么样子的呢？ 我生成的三维模型的效果是这样，是哪里出现问题了吗？
![image](https://user-images.githubusercontent.com/94040073/205304781-3592cb4b-dcc4-4d35-959c-f3f6c18c318e.png)

**Comment by wusidong** [comment]
> 试过，可行，非常感谢
你好，请问你生成三维模型的效果是什么样子的呢？ 我生成的三维模型的效果是这样，是哪里出现问题了吗？
![image](https://user-images.githubusercontent.com/94040073/205305275-a7576e89-4995-41f4-aa55-4a3dea32523f.png)

**Comment by ZhangLei999** [comment]
你代码改了没，训练环境是不是跟作者一样的

**Comment by wusidong** [comment]
我重新训练了一下，现在的结果如下，感觉头发的生成效果有点问题
![image](https://user-images.githubusercontent.com/94040073/205670481-9ba7f0d0-d90e-42ce-9a20-bcb05ce5907b.png)

**Comment by hzhao1997** [comment]
> 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准

有哪些SDK? 我只知道有一个app可以做，不过是基于RGBD的。

**Comment by Gary-Qinghua** [comment]
> > 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准
> 
> 有哪些SDK? 我只知道有一个app可以做，不过是基于RGBD的。

华为的 HMS CORE可以，楼上说的[instant-ngp](https://github.com/NVlabs/instant-ngp)，这个倒是可以建模，但nerf这种建模非OBJ格式，感觉没啥用，转成OBJ的话又太粗糙

**Comment by zhangxujinsh** [comment]
> > > 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准
> > 
> > 
> > 有哪些SDK? 我只知道有一个app可以做，不过是基于RGBD的。
> 
> 华为的 HMS CORE可以，楼上说的[instant-ngp](https://github.com/NVlabs/instant-ngp)，这个倒是可以建模，但nerf这种建模非OBJ格式，感觉没啥用，转成OBJ的话又太粗糙


https://developer.huawei.com/consumer/cn/doc/development/graphics-Guides/introduction-0000001143077297
需要上传到后台服务器，且不支持人脸、人体建模。

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。

**Comment by zhangxujinsh** [comment]
> 

能告知是哪一个app吗？

**Comment by zhangxujinsh** [comment]
> > 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准
> 
> 有哪些SDK? 我只知道有一个app可以做，不过是基于RGBD的。

@hzhao1997  可否告知app的名称？

**Comment by Alane-Henry** [comment]
> > 顺便问一下作者，现在的人体重建，一些厂商的SDK用手机扫一圈，10秒之内就能出一个精度很高的带纹理的模型。请问这种方案，是怎么实现的啊，又快又准
> 
> 有哪些SDK? 我只知道有一个app可以做，不过是基于RGBD的。

请问这个APP是？

**Comment by xiegongsheldon** [comment]
谢谢！邮件已收到。
