### ISSUE TITLE
如何获得有纹理的.obj文件

### ISSUE THREAD

**Issue by wusidong** [hzhao1997/HF-Avatar#9]
from geometry_model.network import diff_optimizer
t=diff_optimizer('cuda','/mnt/8T/zh/vrc','Body2D_2040_499')
t.write_tpose_obj('./')

我想要获得有纹理的三维模型，我在colab运行了上面的代码，但出现了下面的报错，可以告诉我出错原因吗？万分感谢！

[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/) in __getattr__(self, name)  
777                                return modules[name]  
778                 raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
--> 779               type(self).__name__, name))    
780     
781     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:
ModuleAttributeError: 'diff_optimizer' object has no attribute 'v_shaped_personal'

**Comment by hzhao1997** [comment]
请看 https://github.com/hzhao1997/HF-Avatar/issues/7#issuecomment-1333318282

**Comment by wusidong** [comment]
thanks !
